# Generated by Django 3.1.1 on 2020-09-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200901_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='status',
            new_name='checked',
        ),
    ]
